micronaut:
  application:
    name: chatbot-rag
  server:
    port: 8080

ai:
  ollama:
    host: ${OLLAMA_HOST:localhost}
    port: ${OLLAMA_PORT:11434}
    default-model: ${OLLAMA_MODEL:llama3.2}
    timeout: ${OLLAMA_TIMEOUT:60s}